spring:
  application:
    name: api-gateway-server #服务名称
  cloud: #配置SpringCloudGateway的路由
    gateway:
      routes:
#        - id: service1_v1
#          uri: http://localhost:8081/v1
#          predicates:
#            - Path=/test
#        - id: custom
#          uri: lb://eureka-client
#          predicates:
#            - Path=/test/**
#          filters:
#            - name: Example
#              args:
#                op: root
#                type: he
        - id: hello_v1
          uri: lb://eureka-client
          predicates:
            - Path=/test/**
          filters:
            - name: Hello
              args:
                op: root
                type: he
#spring:
#  application:
#    name: gateway-server
#  # 当访问http://localhost:8080/jd直接转发到京东商城首页
#  # 当访问http://localhost:8080/baidu直接转发到https://www.baidu.com/
#  cloud:
#    gateway:
#      routes:
#        - id: service1_v1
#          uri: http://localhost:8081/v1
#          predicates:
#            - Path=/test
#            - Weight=service1, 95
#        - id: service1_v2
#          uri: http://localhost:8081/v2
#          predicates:
#            - Path=/test
#            - Weight=service1, 5
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

#        - id: jd_route
#          uri: https://www.jd.com/
#          predicates:
#            - Path=/jd
#        - id: baidu_route
#          uri: http://baidu.com:80/
#          predicates:
#            - Path=/baidu
#          filters:
#            - StripPrefix=1
#        - id: sc-consumer
#          uri: lb://EUREKA-CLIENT
#          predicates:
#            - Path=/EUREKA-CLIENT/**
#          filters:
#            - RewritePath=/EUREKA-CLIENT/(?<segment>.*),/$\{segment}
#        - id: baidu_route
#          uri: http://baidu.com:80/
#          predicates:
#            - Path=/baidu/test/**
#          filters:
#            - StripPrefix=2
#        - id: prefix_route
#          url: lb://eureka-client
#          predicates:
#            - Path=/test/*
#          filters:
#            - name: Hystrix  # Hystrix Filter的名称
#              args:
#                name: fallbackcmd
#                fallbackUri: forward:/fallback

# hystrix的fallbackcmd的时间
hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
