spring:
  application:
    name: gateway-server
  # 当访问http://localhost:8080/jd直接转发到京东商城首页
  # 当访问http://localhost:8080/baidu直接转发到https://www.baidu.com/
  cloud:
    gateway:
      routes:
#        - id: jd_route
#          uri: https://www.jd.com/
#          predicates:
#            - Path=/jd
#        - id: baidu_route
#          uri: http://baidu.com:80/
#          predicates:
#            - Path=/baidu
#          filters:
#            - StripPrefix=1
        - id: baidu_route
          uri: http://baidu.com:80/
          predicates:
            - Path=/baidu/test/**
          filters:
            - StripPrefix=2
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

