spring:
  application:
    name: zuul-server
server:
  port: 5555
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    # 将所有/client开头的url映射到client-a这个服务中去，
    client-a:
      path: /client/**
      serviceId: client-a
# 禁止ribbon使用eureka,如果设置禁用将找不到微服务client-a
ribbon:
  eureka:
    enabled: true
