spring:
  application:
    name: auth-server
server:
  port: 7777
  servlet:
    context-path: /uua #web基路径
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

